<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MusicRadio.BackEnd.Domain.Entities\MusicRadio.BackEnd.Domain.Entities.csproj" />
    <ProjectReference Include="..\MusicRadio.BackEnd.Infrastructure.Framework\MusicRadio.BackEnd.Infrastructure.Framework.csproj" />
  </ItemGroup>

</Project>
